const menu = [
  {
    id: 1,
    title: 'Rose',
    price: '1,199',
    img: './images/1.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 2,
    title: 'Denim',
    price: '1,999',
    img: './images/2.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'WinterCollection',
  },
  {
    id: 3,
    title: 'Denim',
    price: '1,199',
    img: './images/5.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'WinterCollection',
  },
  {
    id: 4,
    title: 'Denim',
    price: '1,999',
    img: './images/4.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'WinterCollection',
  },
  {
    id: 5,
    title: 'T-Shirt',
    price: '1,199',
    img: './images/5.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 6,
    title: 'Splash',
    price: '1,199',
    img: './images/6.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 7,
    title: 'T-Shirt',
    price: '950',
    img: './images/7.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 8,
    title: 'Rose',
    price: '1,999',
    img: './images/8.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 9,
    title: 'Denim',
    price: '1,500',
    img: './images/9.jpg',
    desc: 'Keeping up the cold with a big dose of style! Shop the ',
    category: 'WinterCollection',
  },
  {
    id: 10,
    title: 'Street Wear',
    price: '1,199',
    img: './images/10.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 11,
    title: 'Lapata',
    price: '950',
    img: './images/11.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 12,
    title: 'T-Shirt',
    price: '850',
    img: './images/12.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 13,
    title: 'Splash',
    price: '1,999',
    img: './images/13.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 14,
    title: 'T-shirt',
    price: '1,999',
    img: './images/14.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 14,
    title: 'T-shirt',
    price: '1,999',
    img: './images/14.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 14,
    title: 'T-shirt',
    price: '1,999',
    img: './images/14.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 15,
    title: 'Splash',
    price: '1,199',
    img: './images/6.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 16,
    title: 'T-Shirt',
    price: '950',
    img: './images/7.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
  {
    id: 17,
    title: 'Rose',
    price: '1,999',
    img: './images/8.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'SummerCollection',
  },
];
export default menu;

