const menu = [
  {
    id: 1,
    title: 'Rose',
    price: '1,199',
    img: './images/1.jpg',
    desc: `Rose, great article! Pasted at the very heart of our black sweatshirt! All sizes available.`,
    category: 'SummerCollection',
  },
  {
    id: 2,
    title: 'Denim',
    price: '1,999',
    img: './images/2.jpg',
    desc: `Denim jackets that compliment everyone’s winter style.`,
    category: 'WinterCollection',
  },
  {
    id: 3,
    title: 'Denim',
    price: '1,999',
    img: './images/3.jpg',
    desc: `Denim jackets that compliment everyone’s winter style.`,
    category: 'WinterCollection',
  },
  {
    id: 4,
    title: 'Denim',
    price: '1,999',
    img: './images/4.jpg',
    desc: `Keeping up the cold with a big dose of style! Shop the coolest winter wear on the block at 30-50% OFF`,
    category: 'WinterCollection',
  },
  {
    id: 5,
    title: '‘میرا جی نہیں لگتا’',
    price: '1,199',
    img: './images/5.jpg',
    desc: `FIRST LOOK: ‘میرا جی نہیں لگتا’ navy blue T-shirt`,
    category: 'SummerCollection',
  },
  {
    id: 6,
    title: 'Splash',
    price: '1,199',
    img: './images/6.jpg',
    desc: `Calling out ALL shoppers, from the snatcher to the hoarder, the line-cutter to the impulsive buyer, the indecisive shopper, and the sale-spy, we’ve got everything for everyone at UP TO 70% OFF! Winterflow 2.0 coming soon.`,
    category: 'SummerCollection',
  },
  {
    id: 7,
    title: 'فتور',
    price: '950',
    img: './images/7.jpg',
    desc: `Have you decided to cash in on our current summer sale?`,
    category: 'SummerCollection',
  },
  {
    id: 8,
    title: 'Rose',
    price: '1,199',
    img: './images/8.jpg',
    desc: `Relax and Unwind with this comfy t-shirt and classic shorts! Shop these pieces from Unwind.`,
    category: 'SummerCollection',
  },
  {
    id: 9,
    title: 'Street Wear',
    price: '1,500',
    img: './images/9.jpg',
    desc: `We highly appreciate you guys, everyone of you. We make sure to give you love through our clothing, so you guys could wear love’
    K-Town is our faith.`,
    category: 'SummerCollection',
  },
  {
    id: 10,
    title: 'Street Wear',
    price: '1,199',
    img: './images/10.jpg',
    desc: `Streetwear style is generally accepted to have been born out of the New York City hip hop culture of the late 1970s and early 1980s, with elements of Los Angeles surf culture. In the mid to late 90s, influences included skateboarding and gangsta rap.`,
    category: 'SummerCollection',
  },
  {
    id: 11,
    title: 'Lapata',
    price: '950',
    img: './images/11.jpg',
    desc: `“Your soul feels so much like home, and when I met you, I finally understood what they mean when they say, ‘Not all who wander are lost”.
    Dropping لاپتہ`,
    category: 'SummerCollection',
  },
  {
    id: 12,
    title: 'Nerds',
    price: '850',
    img: './images/12.jpg',
    desc: `Transitioning into the new season in style. Shop these pieces from Unwind.`,
    category: 'SummerCollection',
  },
  {
    id: 13,
    title: 'Splash',
    price: '1,150',
    img: './images/13.jpg',
    desc: `Only i can see the world. Winterflow 2.0 coming soon`,
    category: 'SummerCollection',
  },
  {
    id: 14,
    title: 'Faith',
    price: '1,999',
    img: './images/14.jpg',
    desc: `FAITH is unseen but felt. So you guys could wear love’ K-Town is our faith`,
    category: 'SummerCollection',
  },
  {
    id: 15,
    title: 'Killin It & Basic',
    price: 'Pack of 2 in 1500',
    img: './images/15.jpg',
    desc: `Calling out ALL shoppers, from the snatcher to the hoarder, the line-cutter to the impulsive buyer, the indecisive shopper, and the sale-spy, we’ve got everything for everyone at UP TO 70% OFF! Winterflow 2.0 coming soon.`,
    category: 'SummerCollection',
  },
  {
    id: 16,
    title: 'K-TOWN',
    price: '1,999',
    img: './images/16.jpg',
    desc: `Dress like there’s no tomorrow! No need to worry about owning hype culture when you’re wearing our outfits!`,
    category: 'SummerCollection',
  },
  {
    id: 17,
    title: 'K-TOWN',
    price: '999',
    img: './images/17.jpg',
    desc: `All around us, *K-TOWN* kept moving! Dropping token of love for Karachities as Karachi is more than just the lights. It has a lively culture unlike any other country, all the chaotic socities, the elegant clothing, the breathtaking art, the philanthropic people.
    3. A *PROTAGONIST* is sometimes a hero to the audience.`,
    category: 'SummerCollection',
  },
  {
    id: 18,
    title: 'PROTAGONIST',
    price: '950',
    img: './images/18.jpg',
    desc: `A *PROTAGONIST* is sometimes a hero to the audience. Heroes gonna wear hero’s tee.`,
    category: 'SummerCollection',
  },
  {
    id: 19,
    title: 'Splash',
    price: '850',
    img: './images/19.jpg',
    desc: `Grab these oversized funky T-shirts in carrot colour and kill the vibes.`,
    category: 'SummerCollection',
  },
  {
    id: 20,
    title: 'Dollar',
    price: '850',
    img: './images/20.jpg',
    desc: `time to fill up your closets with our variety of t-shirts of comfy quality and slay in your gatherings with baggy fashion.`,
    category: 'SummerCollection',
  },
];
export default menu;